Repository hemssy/KiosCorn-iOS, pull requests merged in 2025-09, with the labels that each got.

#2 [Rename] #1 폴더정리
  kioskApp/.DS_Store
  kioskApp/kioskApp.xcodeproj/project.pbxproj
  kioskApp/kioskApp.xcodeproj/project.xcworkspace/xcuserdata/sinseoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  kioskApp/kioskApp/AppDelegate/AppDelegate.swift
  kioskApp/kioskApp/AppDelegate/SceneDelegate.swift
  kioskApp/kioskApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/Contents.json
  kioskApp/kioskApp/Resources/Base.lproj/LaunchScreen.storyboard
  kioskApp/kioskApp/Resources/Info.plist
  kioskApp/kioskApp/ViewController/ViewController.swift
Labels: 🔖 Rename

#10 [Feat] #3 장바구니 UI / 모달 구현
  kioskApp/.DS_Store
  kioskApp/kioskApp.xcodeproj/project.pbxproj
  kioskApp/kioskApp/Resources/Assets.xcassets/DefaultColor.colorset/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/PointColor.colorset/Contents.json
  kioskApp/kioskApp/ViewController/OrderTableViewCell.swift
  kioskApp/kioskApp/ViewController/PaymentPopUp.swift
  kioskApp/kioskApp/ViewController/ViewController.swift
Labels: ✨ Feature

#14 [Feat] 취소 및 결제 버튼 / 수량 스텝퍼 추가
  kioskApp/kioskApp/Resources/Assets.xcassets/ColorCode/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/ColorCode/DefaultColor.colorset/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/ColorCode/PointColor.colorset/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/ColorCode/StepperColor.colorset/Contents.json
  kioskApp/kioskApp/ViewController/MainOrderButton.swift
  kioskApp/kioskApp/ViewController/OrderTableViewCell.swift
  kioskApp/kioskApp/ViewController/PaymentPopUp.swift
  kioskApp/kioskApp/ViewController/ViewController.swift
Labels: ✨ Feature

#19 [Feat] #15 - 셀 커스텀 (장바구니 리스트 UI)
  kioskApp/kioskApp/ViewController/OrderTableViewCell.swift
  kioskApp/kioskApp/ViewController/PaymentPopUp.swift
Labels: ✨ Feature

#23 [Design] #22 - 앱아이콘 추가
  kioskApp/kioskApp.xcodeproj/project.xcworkspace/xcuserdata/sinseoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-1024x1024.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-20x20@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-20x20@3x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-29x29@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-29x29@3x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-38x38@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-38x38@3x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-40x40@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-40x40@3x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-60x60@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-60x60@3x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-64x64@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-64x64@3x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-68x68@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-76x76@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-ios-83.5x83.5@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-128x128.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-128x128@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-16x16.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-16x16@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-256x256.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-256x256@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-32x32.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-32x32@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-512x512.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-mac-512x512@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-1024x1024.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-108x108@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-117x117@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-129x129@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-22x22@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-24x24@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-27.5x27.5@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-29x29@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-30x30@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-32x32@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-33x33@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-40x40@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-43.5x43.5@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-44x44@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-46x46@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-50x50@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-51x51@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-54x54@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-86x86@2x.png
  kioskApp/kioskApp/Resources/Assets.xcassets/AppIcon.appiconset/icon-watchos-98x98@2x.png
Labels: 🎨 Design

#29 [Feat] #20 - Stepper 수량 카운팅, 장바구니 총 가격 계산
  kioskApp/kioskApp.xcodeproj/project.pbxproj
  kioskApp/kioskApp/ViewController/OrderTableViewCell.swift
  kioskApp/kioskApp/ViewController/PaymentPopUp.swift
Labels: ✨ Feature

#34 [Feat] #27 - 직원호출 버튼 alert 추가
  kioskApp/kioskApp.xcodeproj/project.xcworkspace/xcuserdata/sinseoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  kioskApp/kioskApp/ViewController/ViewController.swift
Labels: ✨ Feature

#39 [Fix] braces 실수 수정
  kioskApp/kioskApp.xcodeproj/project.xcworkspace/xcuserdata/sinseoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  kioskApp/kioskApp/ViewController/ViewController.swift
Labels: 🐞 BugFix

#41 [Fix] 직원호출 메서드 사라짐 해결
  kioskApp/kioskApp.xcodeproj/project.xcworkspace/xcuserdata/sinseoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  kioskApp/kioskApp/ViewController/PaymentPopUpViewController.swift
Labels: 🐞 BugFix

#46 [Fix] #44 - 알럿 오류해결
  kioskApp/kioskApp.xcodeproj/project.xcworkspace/xcuserdata/sinseoyeon.xcuserdatad/UserInterfaceState.xcuserstate
  kioskApp/kioskApp/ViewController/PaymentPopUp.swift
  kioskApp/kioskApp/ViewController/PaymentPopUpViewController.swift
  kioskApp/kioskApp/ViewController/ViewController.swift
Labels: 🐞 BugFix
